# SPDX-FileCopyrightText: 2024 Sefa Eyeoglu <contact@scrumplex.net>
#
# SPDX-License-Identifier: CC0-1.0

[envision-unwrapped]
cargo_locks = ["Cargo.lock"]
fetch.git = "https://gitlab.com/gabmus/envision.git"
src.git = "https://gitlab.com/gabmus/envision.git"

[index_camera_passthrough]
cargo_locks = ["Cargo.lock"]
fetch.git = "https://github.com/yshui/index_camera_passthrough.git"
src.git = "https://github.com/yshui/index_camera_passthrough.git"

[monado]
fetch.git = "https://gitlab.freedesktop.org/monado/monado.git"
src.git = "https://gitlab.freedesktop.org/monado/monado.git"

[opencomposite]
fetch.git = "https://gitlab.com/znixian/OpenOVR.git"
git.fetchSubmodules = true
src.git = "https://gitlab.com/znixian/OpenOVR.git"

[wlx-overlay-s]
cargo_locks = ["Cargo.lock"]
fetch.git = "https://github.com/galister/wlx-overlay-s.git"
src.git = "https://github.com/galister/wlx-overlay-s.git"
