name: Update lockfiles

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-locks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24

      - name: Set Git user info
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Update flake inputs
        run: |
          nix flake update --commit-lock-file --commit-lockfile-summary "chore: update flake.lock"

      - name: Update upstream sources
        run: |
          nix develop -c nvfetcher

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.LOCKFILE_TOKEN }}
          base: "main"
          branch: "update-locks"
          delete-branch: true
          committer: github-actions[bot] github-actions[bot]@users.noreply.github.com
          commit-message: "chore: update nvfetcher sources"
          title: "chore: update locks"
          body: "Automated pull request to update flake.lock and nvfetcher sources"
