name: Update lockfiles

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-locks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Set Git user info
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Update flake inputs
        run: |
          nix flake update --commit-lock-file

      - name: Update upstream sources
        run: |
          nix develop -c nvfetcher --commit-changes

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          base: "main"
          branch: "update-locks"
          delete-branch: true
          title: "chore: update locks"
          body: "Automated pull request to update flake.lock and nvfetcher sources"
